export * from './actor.service';
import { ActorService } from './actor.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './genre.service';
import { GenreService } from './genre.service';
export * from './movie.service';
import { MovieService } from './movie.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [ActorService, AuthenticationService, GenreService, MovieService, UserService];
